#!/bin/bash
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/standard-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/acc-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/alias_db-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/auth_db-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/avpops-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/clusterer-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/dialog-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/dialplan-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/dispatcher-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/domain-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/drouting-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/group-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/load_balancer-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/msilo-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/permissions-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/rtpproxy-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/rtpengine-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/speeddial-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/tls_mgm-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/usrloc-create.sql	
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/presence-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /usr/share/opensips/mysql/registrant-create.sql
mysql --host=core-mariadb --user=opensips --password=opensipsrw opensips < /var/www/opensips-cp/config/db_schema.mysql